version: '3.8'

services:
  mysql:
    image: mysql:8.0 # MySQL 버전
    container_name: doitu-mysql-container
    restart: always
    ports:
      - "3307:3306" # 호스트와 컨테이너의 MySQL 포트 매핑
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: doitu
      TZ: Asia/Seoul
    volumes:
      - ./mysql_data:/var/lib/mysql # 데이터 영구 저장
      - ./db/mysql/init:/docker-entrypoint-initdb.d
