spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: user
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql : true
  session:
    store-type: jdbc      # 세션 저장 방식 설정 (메모리: none, DB: jdbc, Redis: redis)
    jdbc:
      initialize-schema: always   # 필요한 경우 테이블 자동 생성
server:
  servlet:
    session:
      timeout: 30m       # 세션 유효 시간 설정 (30분)
